import type { Metadata } from 'next'
import { Overpass_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Navigation } from './components/Navigation'

const overpass = Overpass_Mono({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
