import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "../globals.css";
import React from "react";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const overpassFont = Overpass({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  fallback: ['Roboto']
})

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {

  const messages = useMessages()

  return (
    <html lang={locale}>
      <head>
        <meta httpEquiv="Content-Type" content="text/html;charset=UTF-8" />
      </head>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className={overpassFont.className}>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
